"""Type stubs for the keyring package."""

class KeyringBackend:
    """Base class for keyring backends."""

    name: str

    def get_password(self, service: str, username: str) -> str | None: ...
    def set_password(self, service: str, username: str, password: str) -> None: ...
    def delete_password(self, service: str, username: str) -> None: ...

def get_keyring() -> KeyringBackend: ...
