name: Deploy MkDocs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: .github/workflows/deploy-mkdocs.yml

      - run: pip install properdocs mkdocs-material mkdocs-literate-nav "mkdocstrings[python]" pymdown-extensions

      - run: properdocs gh-deploy --force
        env:
          DISABLE_MKDOCS_2_WARNING: "true"